[package]
name = "revezone-api"
version = "0.1.0"
edition = "2021"

[dev-dependencies]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
#
# Lang libs.
regex = "1.10.3"
chrono = { version = "0.4.38", features = ["serde"] }
uuid = { version = "1.9.1", default-features = false, features = ["v4"] }
thiserror = "1.0.61"
anyhow = "1.0.86"
once_cell = "1.19.0"
#
# Config libs.
config = "0.14.0"
#
# Command line libs.
clap = "4.5.7"
# Serialization libs.
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.64"
serde_yaml = "0.9.32"
#
# Logger libs.
env_logger = "0.11.3"
log = "0.4.22"
#
# Prometheus libs.
lazy_static = "1.4.0"
prometheus = "0.13.4"
axum-prometheus = "0.6.1"
#
# Tracing libs.
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["json", "env-filter"] }
#
# Async core libs.
tokio = { version = "1.38.0", features = ["full", "tracing"] }
console-subscriber = "0.3.0"
#tokio-console = "0.1.11"
#
# Web HTTP libs.
axum = { version = "0.7.5" }
hyper = { version = "1.3.1", features = ["full"] }
tower = "0.4.1"
tower-http = { version = "0.5.2", features = ["trace"] }
#
# Database libs.
mongo = "0.1.0"
# mongodb = "2.8.2"
sqlx = { version = "0.7.4", features = [
    "runtime-tokio-rustls",
    "sqlite",
    "chrono"
] }

[[bin]]
name = "revezone_api"
# path = "src/cmd/api.rs"
path = "src/main.rs"

# [[bin]]
# name = "revezone_cli"
# path = "src/cmd/cli.rs"
[build]
# Enable experimental, but invalid?
# valid command-line: RUSTFLAGS="--cfg tokio_unstable" && cargo build
# see:https://github.com/wl4g-collect/tokio-rs-console/tree/main/console-subscriber#enabling-tokio-instrumentation
rustflags = ["--cfg", "tokio_unstable"]
